echo "[INFO] jenkins : Hello to jenkins file !"
echo "[INFO] jenkins : Here are the information to reach our Jenkins page :"
echo "[INFO] jenkins :    url : \t  http://134.59.213.133:8010/ (must be connected to school VPN)"
echo "[INFO] jenkins :    username : \t  teamc"
echo "[INFO] jenkins :    password : \t  Qqtsv57s"
echo "[INFO] jenkins : Bye !"